/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TherapistFeedback = IDL.Record({
  'feedbackText' : IDL.Text,
  'timestamp' : Time,
  'therapist' : IDL.Principal,
});
export const TherapyTask = IDL.Variant({
  'cognitiveTask' : IDL.Text,
  'speechTask' : IDL.Text,
  'motorTask' : IDL.Text,
});
export const TherapySession = IDL.Record({
  'task' : TherapyTask,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'sessionId' : IDL.Text,
});
export const PatientTreatmentPlanView = IDL.Record({
  'patientId' : IDL.Principal,
  'feedback' : IDL.Vec(TherapistFeedback),
  'sessions' : IDL.Vec(TherapySession),
  'recoveryTrend' : IDL.Text,
});
export const TherapyType = IDL.Variant({
  'motorSkills' : IDL.Null,
  'cognitivePhysical' : IDL.Null,
  'speech' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'therapyType' : IDL.Opt(TherapyType),
  'enrolledModules' : IDL.Vec(IDL.Text),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTherapistFeedback' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchCallerPlan' : IDL.Func([], [PatientTreatmentPlanView], ['query']),
  'fetchCallerSessions' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'fetchSessionScores' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'fetchSpeechExercises' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'fetchTreatmentPlan' : IDL.Func(
      [IDL.Principal],
      [PatientTreatmentPlanView],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listPatients' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitSession' : IDL.Func([TherapyTask, IDL.Nat], [], []),
  'updateRecoveryTrend' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TherapistFeedback = IDL.Record({
    'feedbackText' : IDL.Text,
    'timestamp' : Time,
    'therapist' : IDL.Principal,
  });
  const TherapyTask = IDL.Variant({
    'cognitiveTask' : IDL.Text,
    'speechTask' : IDL.Text,
    'motorTask' : IDL.Text,
  });
  const TherapySession = IDL.Record({
    'task' : TherapyTask,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
  });
  const PatientTreatmentPlanView = IDL.Record({
    'patientId' : IDL.Principal,
    'feedback' : IDL.Vec(TherapistFeedback),
    'sessions' : IDL.Vec(TherapySession),
    'recoveryTrend' : IDL.Text,
  });
  const TherapyType = IDL.Variant({
    'motorSkills' : IDL.Null,
    'cognitivePhysical' : IDL.Null,
    'speech' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'therapyType' : IDL.Opt(TherapyType),
    'enrolledModules' : IDL.Vec(IDL.Text),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTherapistFeedback' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchCallerPlan' : IDL.Func([], [PatientTreatmentPlanView], ['query']),
    'fetchCallerSessions' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'fetchSessionScores' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'fetchSpeechExercises' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'fetchTreatmentPlan' : IDL.Func(
        [IDL.Principal],
        [PatientTreatmentPlanView],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listPatients' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitSession' : IDL.Func([TherapyTask, IDL.Nat], [], []),
    'updateRecoveryTrend' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };