/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PatientTreatmentPlanView {
  'patientId' : Principal,
  'feedback' : Array<TherapistFeedback>,
  'sessions' : Array<TherapySession>,
  'recoveryTrend' : string,
}
export interface TherapistFeedback {
  'feedbackText' : string,
  'timestamp' : Time,
  'therapist' : Principal,
}
export interface TherapySession {
  'task' : TherapyTask,
  'score' : bigint,
  'timestamp' : Time,
  'sessionId' : string,
}
export type TherapyTask = { 'cognitiveTask' : string } |
  { 'speechTask' : string } |
  { 'motorTask' : string };
export type TherapyType = { 'motorSkills' : null } |
  { 'cognitivePhysical' : null } |
  { 'speech' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'therapyType' : [] | [TherapyType],
  'enrolledModules' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Therapists add written feedback to a patient's plan.
   */
  'addTherapistFeedback' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assign a role to a user. Only admins may call this (enforced inside assignRole).
   */
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / An approved patient fetches their own treatment plan.
   */
  'fetchCallerPlan' : ActorMethod<[], PatientTreatmentPlanView>,
  /**
   * / An approved patient fetches their own session scores.
   */
  'fetchCallerSessions' : ActorMethod<[], Array<bigint>>,
  /**
   * / Therapists fetch a specific patient's session scores.
   */
  'fetchSessionScores' : ActorMethod<[Principal], Array<bigint>>,
  /**
   * / Only authenticated users can fetch exercises; guests cannot.
   */
  'fetchSpeechExercises' : ActorMethod<[], Array<string>>,
  /**
   * / Therapists fetch a specific patient's full treatment plan.
   */
  'fetchTreatmentPlan' : ActorMethod<[Principal], PatientTreatmentPlanView>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Any caller (including guests) can check approval status — used by the ApprovalGate UI.
   */
  'isCallerApproved' : ActorMethod<[], boolean>,
  /**
   * / Only admins (therapists) can list all approval requests.
   */
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  /**
   * / Therapists can list all patients who have a treatment plan.
   */
  'listPatients' : ActorMethod<[], Array<Principal>>,
  /**
   * / Only authenticated users (#user) can request approval.
   * / Guests / anonymous principals cannot request access.
   */
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Only admins (therapists) can approve or reject patients.
   */
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Approved patients submit their own therapy sessions.
   * / Admins (therapists) are explicitly blocked from submitting patient sessions
   * / via this endpoint; they use addTherapistFeedback instead.
   */
  'submitSession' : ActorMethod<[TherapyTask, bigint], undefined>,
  /**
   * / Therapists update the computed recovery trend for a patient.
   */
  'updateRecoveryTrend' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];